add_newline = false

[character]
success_symbol = "[âœ](bold green) "
error_symbol = "[âœ—](bold red) "

[git_branch]
symbol = 'ğŸŒ± '
truncation_length = 4
truncation_symbol = ''
# ignore_branches = ['master', 'main']

[python]
symbol = "ğŸ "
python_binary = ['./venv/bin/python', 'python', 'python3']
version_format = "v${major}.${minor}"
style = "yellow bold"

[directory]
style = "cyan bold"
truncation_length = 2
truncation_symbol = 'â€¦/'

[aws]
format = 'on [$profile:<$region>]($style) '
style = 'bold blue'
symbol = 'ğŸ…° '
force_display = true

[line_break]
disabled = true


# mkdir -p ~/.config && touch ~/.config/starship.toml
# code ~/.config/starship.toml
